---
driver:
name: vagrant
 
provisioner:
name: chef_solo
 
platforms:
- name: centos-7.3
driver:
customize:
memory: 256
 
suites:
- name: default
run_list:
- recipe[mongodb-docker::default]
attributes:
